# Generated by Django 5.0.6 on 2026-07-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_route_vehicle_stop_route_vehicle_transportassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['class_enrolled', 'fee_type'], 'verbose_name': 'Fee Structure', 'verbose_name_plural': 'Fee Structures'},
        ),
        migrations.AddField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(choices=[('tuition', 'Tuition Fee'), ('library', 'Library Fee'), ('books', 'Books Fee'), ('admission', 'Admission Fee'), ('transport', 'Transport Fee')], default='tuition', max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('class_enrolled', 'fee_type')},
        ),
    ]
