# Generated by Django 5.0.6 on 2026-07-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_academicyear_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectYearPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('no_of_periods', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_plans', to='school.academicyear')),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_plans', to='school.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_plans', to='school.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_plans', to='school.term')),
            ],
            options={
                'verbose_name': 'Subject Year Plan',
                'verbose_name_plural': 'Subject Year Plans',
                'ordering': ['class_enrolled', 'subject', 'start_date'],
            },
        ),
    ]
